language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt -t lib

before_script:
- wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.28.zip -nv
- unzip -q google_appengine_1.8.9.zip
# command to run tests
script: python test_runner.py
